import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import './index.css';
import App from './App.tsx';
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Provider } from "react-redux";
import { store } from "./redux/store";
createRoot(document.getElementById('root')).render(_jsx(StrictMode, { children: _jsxs(Provider, { store: store, children: [_jsx(App, {}), _jsx(ToastContainer, { position: "top-right", autoClose: 5000 })] }) }));
